server:
  port: 9000

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: project-management-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/projects/**

        - id: communication-service-route
          uri: http://localhost:8089
          predicates:
            - Path=/api/conversations/**

        - id: auth-service-route
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**

        - id: role-service-route
          uri: http://localhost:8080
          predicates:
            - Path=/api/roles/**

        - id: user-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:5174"
              - "http://localhost:5175"
              - "http://127.0.0.1:5173"
              - "http://127.0.0.1:5174"
              - "http://127.0.0.1:5175"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

eureka:
  client:
    enabled: false
