spring.application.name=auth-service
spring.datasource.url=jdbc:postgresql://ep-weathered-rain-at8lj7le-pooler.c-9.us-east-1.aws.neon.tech/organization_db?sslmode=require&channel_binding=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_ilNgTv0W3cRM


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=1234567890123456789012345678901234567890123456789012345678901234
jwt.access-expiration=900000
jwt.refresh-expiration=604800000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=brightfati25@gmail.com
spring.mail.password=jrer jurk yjtv mkdd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
